development:
  stripe_publishable_key: pk_test_Av4EGz2o1zlJ5bgifGjh0cVp
  stripe_secret_key: sk_test_cHcHo1NCkYbiJs8i54CeL7DL

production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']

